### PR TITLE
Add basic auth support to InfluxDB connection

### PR DESCRIPTION
**Pull request by rloomans**
In theory, this is all that's needed to add Basic Auth support for the InfluxDB connections, but I won't get a chance to test it until tomorrow.

### CODE REVIEW

**Comment by mad-ady** [comment]
I'm going to wait for you to try it first. I'm not 100% sure it will work. You're setting authentication for LWP, but InfluxDB::HTTP doesn't necessarily inherit the same parameters. 
When you do test, please try different credentials for InfluxDB than Smokeping uses for user auth.

**Comment by rloomans** [comment]
@mad-ady InfluxDB::HTTP reuses the same LWP::UA object for it's connection, so pulling that out and setting the authentication details with the credentials method works fine.

I've tested it now and I have measurements in my smokeping Influx database :)

**Comment by rloomans** [comment]
@mad-ady You may want to do a squash commit when you merge: I accidentally included a commit where my Vim setup did a bunch of clean ups on the file. I've reversed that, but the commit history is a little ugly.

**Comment by mad-ady** [comment]
Thank you for your contribution

**Comment by rloomans** [comment]
@mad-ady I've also sent you a couple of pull requests for the docker image... One that speeds it up a lot, and another that makes it a bit more user friendly.

**Comment by thall-git** [comment]
I'm not sure this still works, or perhaps it was initially designed for Influx 1, which doesn't work with influx 2.   As I'm not a developer by any means, I've been hacking the code with the help of ChatGPT and I think I got it working with Authorized keys, but really not sure.   Wanted to pass along the code, if you wanted to take a look and submit a MR if correct.  

/opt/smokeping/lib/InfluxDB/HTTP.pm

Remove this line: 

my $response = $self->{lwp_user_agent}->post($uri->canonical(), Content => $measurement);

And add: 

my $token = 'YourInfluxDBTokenHere'; # Replace with your actual InfluxDB token

my $response = $self->{lwp_user_agent}->post(
    $uri->canonical(),
    'Content' => $measurement,
    'Authorization' => "Token $token", 
);`

**Comment by mad-ady** [comment]
> I'm not sure this still works, or perhaps it was initially designed for Influx 1, which doesn't work with influx 2. As I'm not a developer by any means, I've been hacking the code with the help of ChatGPT and I think I got it working with Authorized keys, but really not sure. Wanted to pass along the code, if you wanted to take a look and submit a MR if correct.
> 
> /opt/smokeping/lib/InfluxDB/HTTP.pm
> 
> Remove this line:
> 
> my $response = $self->{lwp_user_agent}->post($uri->canonical(), Content => $measurement);
> 
> And add:
> 
> my $token = 'YourInfluxDBTokenHere'; # Replace with your actual InfluxDB token
> 
> my $response = $self->{lwp_user_agent}->post( $uri->canonical(), 'Content' => $measurement, 'Authorization' => "Token $token", );`

Sorry, I haven't been following this repo. Yes, I was using an older influxdb version. Didn't know it changed.

My suggestion is to push this change upstream (to Influxdb::HTTP maintainer), because I'm no longer involved in Smokeping development.

**Pull request merged**
